name = "PSFJ"
uuid = "b1f51746-9e9d-4163-971e-610fed114a33"
authors = ["Cywtim"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
